const shared=['Workout Design','Preparation & Environment','Safety & Adaptability of the Plan','Flow & Time Management'];
const individual=['Verbal Instruction & Cueing','Exercise Demonstrations','Observation & Positioning','Corrections & Feedback','Motivation & Engagement','Modifications, Responsiveness & Safety Decisions'];
const items=['Instructions were easy to understand','Demonstrations helped me understand what to do','Feedback helped me adjust my movement','An option was offered when I needed one','The instructor noticed and responded when I needed help','The instructor encouraged me respectfully'];
const standards=['Appropriate purpose, selection, workload, sequence, progression and backup content. EXS217 also addresses intensity, work/recovery and assigned equipment.','Layout, visuals, music, timer and materials functional and ready at least 5 minutes early.','Safe spacing, traffic flow, sequence, planned modifications and equipment use.','Exact start/end, full 45 minutes, smooth transitions, opening, warm-up, cooldown and closing.','Accurate, concise, audible directions and useful cues at the right time.','Visible, technically accurate demonstrations before participants begin.','Purposeful movement, full-group scanning and useful sight lines.','Timely, accurate, respectful and actionable feedback; checks its effect.','Appropriate energy, acknowledgment of effort and engagement.','Recognizes needs, offers options and involves instructor when beyond student authority.'];
const roleNames=['Front Desk / On Deck','Workout Support'];
const roleStandards=['On time; prepared desk; greeting, orientation, waivers, coverage, handoff, checkout and professional conduct.','Advance communication; punctual, safe setup; attentive observation; specific complete observation form; appropriate assistance; cleanup and reset.','Ready; full-session participation, effort, directions, safe technique, limitations communicated, respect and professional conduct.'];
let state={teamFeedback:[],observerAssignments:{},snapshots:[],values:{},notes:{},feedback:[],observers:[],versions:{}};try{state=JSON.parse(localStorage.getItem('exs-schedule-v2'))||state}catch{}
state.comments ||= {}; state.priorities ||= {}; state.participation ||= {};
for(const map of [state.values,state.notes,state.comments])for(const k of Object.keys(map)){if(k.includes(':team:shared:')){const nk=k.replace(':team:shared:',':team-a:shared:');if(map[nk]===undefined)map[nk]=map[k];delete map[k]}}
state.teamFeedback ||= []; state.observerAssignments ||= {}; state.snapshots ||= [];
state.sessions ||= {}; state.checkins ||= []; state.queue ||= [];
let tab='schedule';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const course=()=>$('#course').value,student=()=>$('#student').value,key=(kind,i)=>assessmentKey(kind,i);
function save(){if(typeof cloudActive!=='undefined'&&cloudActive){queueCloudSave();return}try{localStorage.setItem('exs-schedule-v2',JSON.stringify({...state,schema:'schedule-v2'}));$('#saved').textContent='Sample progress saved in this browser'}catch{$('#saved').textContent='Save failed — export progress before leaving'}}
const avg=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:null,fmt=n=>n===null?'Pending':n.toFixed(2);
function teaching(){if(schedule().sessions[assignment('individual')]?.deferred)return null;const a=[...shared.map((_,i)=>state.values[key('shared',i)]),...individual.map((_,i)=>state.values[key('individual',i)])];return a.every(x=>Number.isInteger(x))?avg(a):null}
function professional(){if(roleNames.some((_,i)=>roleDeferred(i)))return null;let a=roleNames.map((_,i)=>state.values[key('role',i)]);return a.every(x=>Number.isInteger(x))?avg(a):null}
function bankFor(title){return (commentBank[title]||[]).filter(c=>!c.course||c.course===course())}
function commentPanel(title,k){const selected=state.comments[k]||{};return `<details class="comment-bank"><summary>Comment choices (${Object.keys(selected).length} selected)</summary><p>Choose only what you observed. Selections do not change the score.</p>${['strength','refinement','next'].map(g=>`<fieldset><legend>${{strength:'Effective practice',refinement:'Needs refinement',next:'Next step'}[g]}</legend>${bankFor(title).filter(c=>c.group===g).map(c=>`<label class="comment-choice"><input type="checkbox" data-comment-key="${k}" data-comment-id="${c.id}" ${selected[c.id]!==undefined?'checked':''}> ${esc(c.text)}</label><label ${selected[c.id]===undefined?'hidden':''}>Edit selected wording<textarea data-edit-key="${k}" data-edit-id="${c.id}">${esc(selected[c.id]??c.text)}</textarea></label>`).join('')}</fieldset>`).join('')}</details>`}
function conflicts(title,k){const ids=Object.keys(state.comments[k]||{});const groups={};bankFor(title).filter(c=>ids.includes(c.id)&&c.exclusive).forEach(c=>{groups[c.exclusive]=(groups[c.exclusive]||0)+1});return Object.values(groups).some(n=>n>1)}
function compiled(title,k){const selected=state.comments[k]||{};return (conflicts(title,k)?'<p class="warning">Review conflicting timing comments before releasing this report.</p>':'')+['strength','refinement','next'].map(g=>{const texts=[...new Set(bankFor(title).filter(c=>c.group===g&&selected[c.id]!==undefined).map(c=>selected[c.id].trim()).filter(Boolean))];return texts.length?`<h4>${{strength:'Strengths',refinement:'Areas to refine',next:'Next steps'}[g]}</h4><ul>${texts.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}).join('')}
function rating(title,k,standard){const bankTitle=k.includes(':role:')?roleNames[Number(k.split(':').pop())]:title;return `<article><h3>${esc(title)}</h3><details><summary>Competency standard: 3</summary><p>${esc(standard)}</p></details><div class="scores" role="group" aria-label="${esc(title)} rating">${[0,1,2,3,4].map(n=>`<button data-key="${k}" data-score="${n}" aria-pressed="${state.values[k]===n}">${n}</button>`).join('')}<button data-unscore="${k}">Clear rating</button><span>${state.values[k]===undefined?'Unscored':state.values[k]<3?'Below competency standard':''}</span></div>${commentPanel(bankTitle,k)}<label>Additional feedback / specific example<textarea data-note="${k}">${esc(state.notes[k])}</textarea></label></article>`}
function participationPanel(report=false){return `<article><h3>Workout participation</h3><p>Completion record only. Not included in either numeric score.</p>${studentParticipation().map(({i})=>{const k=key('participation',i),value=state.participation[k]||'Pending',label=sessionLabel(i);return report?`<p>${esc(label)}: ${esc(value)}${state.notes[k]?` — ${esc(state.notes[k])}`:''}</p>`:`<label>${esc(label)}<select data-participation="${k}">${['Pending','Completed','Not completed'].map(n=>`<option ${value===n?'selected':''}>${n}</option>`).join('')}</select></label><label>Optional note<textarea data-note="${k}">${esc(state.notes[k])}</textarea></label>`}).join('')}</article>`}
function deferredPanel(title,label){return `<article><h3>${esc(title)}</h3><p class="warning">Awaiting alternate opportunity. ${esc(label)}. No score assigned; excluded from final scoring until assessed.</p></article>`}

function render(){document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab));let h='';if(tab==='schedule')h=scheduleView();if(tab==='checkin')h=checkinView();if(tab==='teaching'){h=`<h2>Teaching · ${esc(student())}</h2><p>Team: ${esc(teamLabel(teamIndex()))}. Teaching: ${esc(assignmentLabel('individual'))}. Shared ratings apply to this team. Individual ratings apply only to the selected student.</p><p>0 No competency · 1 Minimal · 2 Partial · 3 Meets · 4 Exceeds</p><div class="panel metric">Canvas teaching score: ${fmt(teaching())} / 4</div><h2>Shared team criteria</h2>`+(schedule().sessions[assignment('individual')].deferred?deferredPanel('Teaching',assignmentLabel('individual')):shared.map((n,i)=>rating(n,key('shared',i),standards[i])).join('')+'<h2>Individual teaching</h2>'+individual.map((n,i)=>rating(n,key('individual',i),standards[i+4])).join(''))}
if(tab==='roles')h=`<h2>Professional Practice · ${esc(student())}</h2><p>Choose a teaching team above, then the individual student to assess. Front desk and support ratings are individual. Their assigned role dates are shown below. Deferred opportunities stay pending; they are not missing work. Front desk and support count equally. Participation is recorded separately as completion only.</p><div class="panel metric">Canvas Professional Practice: ${fmt(professional())} / 4</div>`+roleNames.map((n,i)=>roleDeferred(i)?deferredPanel(n,assignmentLabel(i)):rating(n+' · '+assignmentLabel(i),key('role',i),roleStandards[i])).join('')+participationPanel();
if(tab==='participant')h=schedule().sessions[teachingIndex()].deferred?deferredPanel('Participant evaluation',assignmentLabel('individual')):participantView();
if(tab==='observer')h=schedule().sessions[teachingIndex()].deferred?deferredPanel('Observer evaluation',assignmentLabel('individual')):observerView();
if(tab==='feedback')h=reviewView();
if(tab==='participant-results')h=participantInboxView();
if(tab==='report')h=reportView();$('#content').innerHTML=h}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reviewSession){$('#course').value=b.dataset.reviewCourse;syncTeams();$('#team').value=b.dataset.reviewTeam;syncStudents();tab='feedback';render()}if(b.dataset.tab){tab=b.dataset.tab;render()}if(b.dataset.key){state.values[b.dataset.key]=Number(b.dataset.score);save();render()}if(b.dataset.unscore){delete state.values[b.dataset.unscore];save();render()}if(b.dataset.sessionAction){setSessionStatus(Number(b.dataset.session),b.dataset.sessionAction);save();render()}if(b.id==='print'){render();const id=`${course()}:${student()}`;state.versions[id]=(state.versions[id]||0)+1;state.snapshots.push({course:course(),student:student(),version:state.versions[id],created:new Date().toISOString(),html:$('#content').innerHTML});save();window.print()}if(b.id==='clear'&&confirm('Delete all sample progress, feedback and notes in this browser?')){state={teamFeedback:[],observerAssignments:{},snapshots:[],values:{},notes:{},feedback:[],observers:[],versions:{},comments:{},priorities:{},participation:{},sessions:{},checkins:[],queue:[]};save();render()}if(b.id==='export'){let u=URL.createObjectURL(new Blob([JSON.stringify({...state,schema:'schedule-v2'})],{type:'application/json'}));let a=document.createElement('a');a.href=u;a.download='exs-sample-progress.json';a.click();URL.revokeObjectURL(u)}});
document.addEventListener('input',e=>{if(e.target.dataset.priority){state.priorities[e.target.dataset.priority]=e.target.value;save()}if(e.target.dataset.editKey){state.comments[e.target.dataset.editKey][e.target.dataset.editId]=e.target.value;save()}if(e.target.dataset.feedbackEdit){const f=state.feedback.find(r=>r.id===e.target.dataset.feedbackEdit);f.edited ||= {};f.edited[e.target.dataset.field]=e.target.value;save()}if(e.target.dataset.teamEdit){state.teamFeedback.find(r=>r.id===e.target.dataset.teamEdit).edited[student()]=e.target.value;save()}if(e.target.dataset.observerEdit){const f=state.observers.find(r=>r.id===e.target.dataset.observerEdit);f.edited ||= [];f.edited[Number(e.target.dataset.answer)]=e.target.value;save()}if(e.target.dataset.note){state.notes[e.target.dataset.note]=e.target.value;save()}});
document.addEventListener('change',e=>{if(e.target.dataset.observerAssignment){let names=assignedObservers().filter(n=>n!==e.target.dataset.observerAssignment);if(e.target.checked){if(names.length>=2){e.target.checked=false;alert('Choose exactly two observers.');return}names.push(e.target.dataset.observerAssignment)}state.observerAssignments[sessionKey(teachingIndex())]=names;save();render()}if(e.target.dataset.teamInclude){const f=state.teamFeedback.find(r=>r.id===e.target.dataset.teamInclude);if(f.permission)f.include[student()]=e.target.checked;save()}if(e.target.dataset.participation){state.participation[e.target.dataset.participation]=e.target.value;save()}if(e.target.dataset.commentKey){const k=e.target.dataset.commentKey,id=e.target.dataset.commentId;state.comments[k] ||= {};const title=k.includes(':shared:')?shared[Number(k.split(':').pop())]:k.includes(':individual:')?individual[Number(k.split(':').pop())]:roleNames[Number(k.split(':').pop())];if(e.target.checked)state.comments[k][id]=bankFor(title).find(c=>c.id===id).text;else delete state.comments[k][id];save();const panel=e.target.closest('.comment-bank');const selection=e.target.closest('label').nextElementSibling;selection.hidden=!e.target.checked;panel.querySelector('summary').textContent=`Comment choices (${Object.keys(state.comments[k]).length} selected)${conflicts(title,k)?' — conflicting timing choices':''}`;}if(e.target.id==='checkin-session'){checkinSelection[course()]=Number(e.target.value);render()}if(e.target.id==='team'){syncStudents();render()}if(e.target.id==='course'){syncTeams();syncStudents();render()}if(e.target.id==='student')render();if(e.target.dataset.include){let [id,k]=e.target.dataset.include.split(':');state.feedback.find(f=>f.id===id).include[k]=e.target.checked;save()}if(e.target.dataset.observer){state.observers.find(f=>f.id===e.target.dataset.observer).include=e.target.checked;save()}});
document.addEventListener('submit',e=>{if(!['checkin-form','participant-form','observer-form'].includes(e.target.id))return;e.preventDefault();let d=new FormData(e.target);if(e.target.id==='checkin-form'){const result=addCheckin(Number(d.get('session')),d.get('email'),d.has('consent'),d.get('name'));if(result){$('#checkin-error').textContent=result;return}try{localStorage.setItem('exs-schedule-v2',JSON.stringify({...state,schema:'schedule-v2'}))}catch{state.checkins.pop();$('#checkin-error').textContent='Check-in could not be saved. Please ask the front desk to try again.';return}render();$('#checkin-confirmation').textContent='You’re checked in. Enjoy your workout!';$('#checkin-name').focus();return}if(e.target.id==='participant-form'){const error=submitParticipant(d);if(error){alert(error);return}}if(e.target.id==='observer-form'){const error=submitObserver(d);if(error){alert(error);return}}save();tab='feedback';render()});
$('#import').addEventListener('change',async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(x.schema!=='schedule-v2'||!x.values||!x.notes||!Array.isArray(x.feedback)||!Array.isArray(x.observers)||!x.versions)throw Error();state=x;state.comments ||= {};state.priorities ||= {};state.participation ||= {};state.teamFeedback ||= [];state.observerAssignments ||= {};state.snapshots ||= [];state.sessions ||= {};state.checkins ||= [];state.queue ||= [];save();render()}catch{alert('This is not a valid sample-progress file.')}});syncTeams();syncStudents();render();

window.addEventListener('storage',e=>{if(e.key!=='exs-schedule-v2'||(typeof cloudActive!=='undefined'&&cloudActive))return;try{const next=JSON.parse(e.newValue);if(next?.schema==='schedule-v2'){state=next;render()}}catch{$('#saved').textContent='Records changed in another window. Reload before continuing.'}});
