const $=s=>document.querySelector(s),course=()=>$('#course').value;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state;
function refresh(){state=JSON.parse(localStorage.getItem('exs-schedule-v2'))||{schema:'schedule-v2',values:{},notes:{},comments:{},priorities:{},participation:{},feedback:[],teamFeedback:[],observers:[],observerAssignments:{},versions:{},snapshots:[],sessions:{},checkins:[],queue:[]};state.sessions ||= {};state.checkins ||= [];state.queue ||= []}
function render(){try{refresh();$('#content').innerHTML=checkinView();renderDeskSetup();configureParticipantMode()}catch{$('#content').innerHTML='<p role="alert">Check-in records could not be opened. Please ask the front desk for help.</p>'}}
document.addEventListener('change',e=>{if(e.target.id==='checkin-session'){checkinSelection[course()]=Number(e.target.value);render()}if(e.target.id==='course')render()});
document.addEventListener('submit',e=>{if(e.target.id!=='checkin-form')return;e.preventDefault();const d=new FormData(e.target);try{refresh();const error=addCheckin(Number(d.get('session')),d.get('email'),d.has('consent'),d.get('name'));if(error){$('#checkin-error').textContent=error;return}localStorage.setItem('exs-schedule-v2',JSON.stringify(state));render();$('#checkin-confirmation').textContent='You’re checked in. Enjoy your workout!';$('#checkin-name')?.focus()}catch{$('#checkin-error').textContent='Check-in could not be saved. Please ask the front desk to try again.'}});
window.addEventListener('storage',e=>{if(e.key==='exs-schedule-v2'){try{refresh();const selected=checkinSelection[course()];if(!checkinOptions().some(o=>o.i===selected))render()}catch{render()}}});
render();

function allWorkoutOptions(){return Object.entries(courseSchedules).flatMap(([c,data])=>data.sessions.map((s,i)=>({c,s,i,key:c+':'+i}))).filter(({c,s,i})=>!s.deferred&&!['Completed','Canceled'].includes(state.sessions[c+':workout-'+(i+1)]))}
function renderDeskSetup(){const box=$('#desk-setup');const active=course()+':'+checkinSelection[course()];box.innerHTML=`<details class="desk-setup"><summary>Front desk: change workout</summary><label for="desk-workout">Workout team and time<select id="desk-workout">${allWorkoutOptions().map(({c,s,i,key})=>`<option value="${key}" ${active===key?'selected':''}>${esc(courseSchedules[c].teams[s.teach].join(' · '))} · ${esc(s.date)} · ${esc(s.time)}</option>`).join('')}</select></label><p>Keep the correct workout selected for arriving participants.</p></details>`}
function configureParticipantMode(){const select=$('#checkin-session');if(select){select.closest('label').hidden=true;} }
document.addEventListener('change',e=>{if(e.target.id==='desk-workout'){const [c,i]=e.target.value.split(':');$('#course').value=c;checkinSelection[c]=Number(i);render()}});
