const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api='/.netlify/functions/public-workouts';
const date=s=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'America/Phoenix'}).format(new Date(s+'T12:00:00Z'));
const time=s=>String(s).replace(/(\d{1,2}:\d{2})\s*[–-]\s*(\d{1,2}:\d{2})$/, '$1–$2 AM')+' (Arizona time)';
let workouts=[],selected='',busy=false,testMode=true;
try{selected=sessionStorage.getItem('workout-desk-selection')||''}catch{}
function render(){const w=workouts.find(w=>w.key===selected);$('#desk-setup').innerHTML=`<details class="desk-setup"><summary>Front desk · choose workout team</summary><label>Workout team<select id="workout-team">${workouts.map(s=>`<option value="${esc(s.key)}" ${s.key===selected?'selected':''}>${esc(s.instructors.join(' · '))} — ${esc(date(s.date))}, ${esc(time(s.time))}</option>`).join('')}</select></label></details>`;$('#content').innerHTML=w?`<div class="checkin-card"><small>MCC · WORKOUT CHECK-IN</small><h1>Welcome. Let’s get moving.</h1><p>Everyone is welcome. Enter your name and email to check in.</p><div class="workout-badge"><strong>${esc(w.instructors.join(' · '))}</strong><span>${esc(date(w.date))}</span><span>${esc(time(w.time))}</span></div>${testMode?'<p class="test-note">Test preview: use a fictional name and an @example.com email. No emails are sent.</p>':'<p class="muted">Your email is used only for this workout’s evaluation invitation.</p>'}<form id="public-checkin"><label>Your name<input id="checkin-name" name="name" maxlength="100" autocomplete="name" required></label><label>Email<input name="email" type="email" maxlength="254" autocomplete="email" placeholder="${testMode?'participant@example.com':'you@email.com'}" required></label><label class="consent"><input name="consent" type="checkbox"> Email me a short workout evaluation after the workout.</label><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><p id="checkin-error" role="alert"></p><button class="checkin-submit">Check in</button></form><div id="checkin-confirmation" role="status" aria-live="polite"></div></div>`:'<div class="checkin-card"><h1>Check-in is closed</h1><p>Please ask the front desk about the next workout.</p></div>'}
document.addEventListener('change',e=>{if(e.target.id==='workout-team'){selected=e.target.value;try{sessionStorage.setItem('workout-desk-selection',selected)}catch{}render()}});
document.addEventListener('submit',async e=>{if(e.target.id!=='public-checkin')return;e.preventDefault();if(busy)return;busy=true;const form=e.target,button=form.querySelector('button'),data=new FormData(form);button.disabled=true;$('#checkin-error').textContent='';$('#checkin-confirmation').textContent='';try{const response=await fetch(api+'?action=checkin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session:selected,name:data.get('name'),email:data.get('email'),consent:data.has('consent'),website:data.get('website')})});const result=await response.json();if(!response.ok)throw Error(result.error);form.reset();$('#checkin-confirmation').innerHTML=`<p><strong>${esc(result.message)}</strong></p>${result.evaluationPath?`<p>For testing: <a href="${esc(result.evaluationPath)}" target="_blank" rel="noopener">Open your evaluation preview</a>. No email was sent.</p>`:''}`;$('#checkin-name').focus()}catch(error){$('#checkin-error').textContent=error.message||'Check-in could not be saved. Please try again.'}finally{busy=false;button.disabled=false}});
(async()=>{try{const response=await fetch(api+'?action=sessions',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);testMode=data.test!==false;workouts=data.sessions.filter(s=>!['Completed','Canceled'].includes(s.status));if(!workouts.some(s=>s.key===selected))selected=workouts[0]?.key||'';render()}catch{$('#content').innerHTML='<div class="checkin-card"><h1>Check-in is unavailable</h1><p>Please ask the front desk to try again.</p><button onclick="location.reload()">Try again</button></div>'}})();
