let cloudActive=false,cloudETag=null,cloudBlocked=false,cloudTimer,cloudSaving=false,cloudDirty=false;
function cloudStatus(text){document.querySelector('#saved').textContent=text}
async function loadOnline(){if(!window.workoutIdentity){cloudStatus('Instructor sign-in is not available yet.');return}const user=await workoutIdentity.getUser();if(!user){document.querySelector('#instructor-login').hidden=false;cloudStatus('Sign in before loading instructor records.');return}const response=await fetch('/.netlify/functions/records',{cache:'no-store'});const data=await response.json();if(!response.ok){cloudStatus(data.error);return}if(!confirm('Load online instructor records? Export any browser-only test work you want to keep first.'))return;state=data.state;cloudETag=data.etag;cloudActive=true;cloudBlocked=false;render();cloudStatus('Protected records loaded. Changes will save online.');}
async function saveOnline(){cloudTimer=null;if(!cloudActive||cloudBlocked)return;if(cloudSaving){cloudDirty=true;return}cloudSaving=true;cloudDirty=false;try{const response=await fetch('/.netlify/functions/records',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:{...state,schema:'schedule-v2'},etag:cloudETag})});const data=await response.json();if(!response.ok){cloudBlocked=true;cloudStatus(data.error+' Export your current work before leaving.');return}cloudETag=data.etag;cloudStatus('Saved online · '+new Date(data.saved).toLocaleTimeString());}finally{cloudSaving=false;if(cloudDirty&&!cloudBlocked)queueCloudSave()}}
function queueCloudSave(){cloudDirty=true;clearTimeout(cloudTimer);cloudStatus('Unsaved online changes…');cloudTimer=setTimeout(()=>saveOnline().catch(()=>{cloudBlocked=true;cloudStatus('Online save failed. Export your current work before leaving.')}),800)}
document.querySelector('#load-online').addEventListener('click',()=>loadOnline().catch(()=>cloudStatus('Online records could not be loaded.')));
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const fields=new FormData(e.target);try{await workoutIdentity.login(fields.get('email'),fields.get('password'));e.target.reset();document.querySelector('#instructor-login').hidden=true;document.querySelector('#signout').hidden=false;cloudStatus('Signed in. Select Load online records.')}catch{document.querySelector('#login-error').textContent='Sign-in did not complete. Check your credentials or ask for account setup.'}});
window.addEventListener('beforeunload',e=>{if(cloudActive&&(cloudBlocked||cloudTimer||cloudSaving||cloudDirty)){e.preventDefault();e.returnValue=''}});

let instructorInviteToken;
(async()=>{try{const result=await workoutIdentity.handleAuthCallback();if(result?.type==='invite'){instructorInviteToken=result.token;document.querySelector('#account-setup').hidden=false;}const user=await workoutIdentity.getUser();document.querySelector('#signout').hidden=!user;}catch{cloudStatus('Account setup could not be completed. Request a fresh invitation.')}})();
document.querySelector('#setup-form').addEventListener('submit',async e=>{e.preventDefault();const fields=new FormData(e.target);if(fields.get('password')!==fields.get('confirmation')){document.querySelector('#setup-error').textContent='Passwords must match.';return}try{await workoutIdentity.acceptInvite(instructorInviteToken,fields.get('password'));instructorInviteToken=null;e.target.reset();document.querySelector('#account-setup').hidden=true;document.querySelector('#signout').hidden=false;cloudStatus('Instructor account ready. Select Load online records.')}catch{document.querySelector('#setup-error').textContent='Setup failed. Try a new invitation or a stronger password.'}});
document.querySelector('#signout').addEventListener('click',async()=>{if(cloudActive&&(cloudBlocked||cloudTimer||cloudSaving||cloudDirty)){cloudStatus('Save or export your current work before signing out.');return}await workoutIdentity.logout();location.reload();});
