let cloudGeneration,cloudTestMode=true;
let cloudActive=false,cloudETag=null,cloudBlocked=false,cloudTimer,cloudSaving=false,cloudDirty=false;
function cloudStatus(text){document.querySelector('#saved').textContent=text}
function showInstructorLogin(){const panel=document.querySelector('#instructor-login');panel.hidden=false;panel.scrollIntoView({block:'center'});panel.querySelector('input').focus();document.querySelector('#signout').hidden=true;}
function recordHeaders(){const match=document.cookie.match(/(?:^|;\s*)nf_jwt=([^;]+)/);return match?{Authorization:'Bearer '+decodeURIComponent(match[1])}:{}}
async function loadOnline(){if(cloudActive&&(cloudTimer||cloudSaving||cloudDirty||cloudBlocked)){cloudStatus('Save or export your current work before loading online records again.');return}if(!window.workoutIdentity){cloudStatus('Instructor sign-in is not available yet.');return}const user=await workoutIdentity.getUser();if(!user){showInstructorLogin();cloudStatus('Sign in before loading instructor records.');return}const response=await fetch('/.netlify/functions/records',{cache:'no-store',headers:recordHeaders()});const data=await response.json();if(!response.ok){if(response.status===401)showInstructorLogin();cloudStatus(data.error);return}state=data.state;cloudETag=data.etag;cloudGeneration=data.generation;cloudTestMode=data.test!==false;if(data.schedules)Object.assign(courseSchedules,data.schedules);syncTeams();syncStudents();cloudActive=true;cloudBlocked=false;updateStorageMode();render();cloudStatus('Protected records loaded. Changes will save online.');await refreshParticipants();}
async function saveOnline(){cloudTimer=null;if(!cloudActive||cloudBlocked)return;if(cloudSaving){cloudDirty=true;return}cloudSaving=true;cloudDirty=false;try{const response=await fetch('/.netlify/functions/records',{method:'PUT',headers:{'Content-Type':'application/json',...recordHeaders()},body:JSON.stringify({state:{...state,schema:'schedule-v2'},etag:cloudETag,generation:cloudGeneration})});const data=await response.json();if(!response.ok){cloudBlocked=true;cloudStatus(data.error+' Export your current work before leaving.');return}cloudETag=data.etag;cloudStatus('Saved online · '+new Date(data.saved).toLocaleTimeString());}finally{cloudSaving=false;if(cloudDirty&&!cloudBlocked)queueCloudSave()}}
function queueCloudSave(){cloudDirty=true;clearTimeout(cloudTimer);cloudStatus('Unsaved online changes…');cloudTimer=setTimeout(()=>saveOnline().catch(()=>{cloudBlocked=true;cloudStatus('Online save failed. Export your current work before leaving.')}),800)}
document.querySelector('#load-online').addEventListener('click',()=>loadOnline().catch(()=>cloudStatus('Online records could not be loaded.')));
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const fields=new FormData(e.target);try{await workoutIdentity.login(fields.get('email'),fields.get('password'));e.target.reset();document.querySelector('#instructor-login').hidden=true;document.querySelector('#signout').hidden=false;cloudStatus('Signed in. Select Load online records.')}catch{document.querySelector('#login-error').textContent='Sign-in did not complete. Check your credentials or ask for account setup.'}});
window.addEventListener('beforeunload',e=>{if(cloudActive&&(cloudBlocked||cloudTimer||cloudSaving||cloudDirty)){e.preventDefault();e.returnValue=''}});

let instructorInviteToken;
(async()=>{try{const result=await workoutIdentity.handleAuthCallback();if(result?.type==='invite'){instructorInviteToken=result.token;document.querySelector('#account-setup').hidden=false;}const user=await workoutIdentity.getUser();document.querySelector('#signout').hidden=!user;}catch{cloudStatus('Account setup could not be completed. Request a fresh invitation.')}})();
document.querySelector('#setup-form').addEventListener('submit',async e=>{e.preventDefault();const fields=new FormData(e.target);if(fields.get('password')!==fields.get('confirmation')){document.querySelector('#setup-error').textContent='Passwords must match.';return}try{await workoutIdentity.acceptInvite(instructorInviteToken,fields.get('password'));instructorInviteToken=null;e.target.reset();document.querySelector('#account-setup').hidden=true;document.querySelector('#signout').hidden=false;cloudStatus('Instructor account ready. Select Load online records.')}catch{document.querySelector('#setup-error').textContent='Setup failed. Try a new invitation or a stronger password.'}});
document.querySelector('#signout').addEventListener('click',async()=>{if(cloudActive&&(cloudBlocked||cloudTimer||cloudSaving||cloudDirty)){cloudStatus('Save or export your current work before signing out.');return}await workoutIdentity.logout();location.reload();});

function updateStorageMode(){document.querySelector('#storage-mode').textContent=cloudActive?(cloudTestMode?'Test preview · Participant emails disabled · Protected online saving':'Live records · Protected online saving'):'Test preview · No emails are sent · Saves in this browser';document.querySelector('#refresh-participants').hidden=!cloudActive;document.querySelector('#clear').disabled=cloudActive;document.querySelector('#check-email').hidden=!cloudActive;document.querySelector('#send-test-email').hidden=!cloudActive;document.querySelector('#launch-setup').hidden=!cloudActive||!cloudTestMode}
async function refreshParticipants(){if(!cloudActive||cloudBlocked){cloudStatus('Load online records before refreshing participant feedback.');return}const button=document.querySelector('#refresh-participants');button.disabled=true;try{const response=await fetch('/.netlify/functions/public-workouts?action=inbox',{cache:'no-store',headers:recordHeaders()}),data=await response.json();if(!response.ok)throw Error(data.error);state.emailStatus=data.emailStatus;state.excludedCheckins=data.excludedCheckins||[];for(const id of data.excludedIds||[]){state.checkins=state.checkins.filter(r=>r.id!==id);state.feedback=state.feedback.filter(r=>r.batch!=='public-'+id);state.teamFeedback=state.teamFeedback.filter(r=>r.batch!=='public-'+id);state.queue=state.queue.filter(r=>r.checkin!==id)}state.queue=state.queue.filter(r=>!r.id.startsWith('public:')||data.invitations.some(q=>q.id===r.id));const merge=(key,rows)=>{const ids=new Set(state[key].map(r=>r.id));for(const row of rows)if(!ids.has(row.id)){state[key].push(row);ids.add(row.id)}};merge('checkins',data.checkins);merge('feedback',data.feedback);merge('teamFeedback',data.teamFeedback);for(const q of data.invitations){const existing=state.queue.find(r=>r.id===q.id);if(existing)Object.assign(existing,q);else state.queue.push(q)}tab='participant-results';save();render()}catch(error){cloudStatus(error.message||'Participant feedback could not be refreshed.')}finally{button.disabled=false}}
document.querySelector('#refresh-participants').addEventListener('click',refreshParticipants);

document.querySelector('#check-email').addEventListener('click',async()=>{const button=document.querySelector('#check-email');button.disabled=true;cloudStatus('Checking email connection…');try{const response=await fetch('/.netlify/functions/email-connection',{method:'POST',headers:recordHeaders()}),data=await response.json();cloudStatus(response.ok?data.message:data.error);}catch{cloudStatus('Email connection check could not be completed. No message was sent.');}finally{button.disabled=false}});

document.querySelector('#send-test-email').addEventListener('click',async()=>{const button=document.querySelector('#send-test-email');button.disabled=true;cloudStatus('Sending one styled test email to your MCC address…');try{const response=await fetch('/.netlify/functions/email-test',{method:'POST',headers:recordHeaders()}),data=await response.json();cloudStatus(data.message||data.error);}catch{cloudStatus('Sending result is uncertain. Check your MCC inbox before retrying.');}});

async function excludeTestCheckin(button){
 if(!cloudActive||cloudBlocked){cloudStatus('Load online records first.');return}
 button.disabled=true;
 try{const response=await fetch('/.netlify/functions/public-workouts?action=exclude-test',{method:'POST',headers:{'Content-Type':'application/json',...recordHeaders()},body:JSON.stringify({session:button.dataset.excludeSession,id:button.dataset.excludeCheckin,excluded:button.dataset.restoreEntry!=='true'})}),data=await response.json();if(!response.ok)throw Error(data.error);await refreshParticipants();cloudStatus(data.message)}catch(error){cloudStatus(error.message||'The test entry could not be excluded.')}finally{button.disabled=false}
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-exclude-checkin]');if(button)excludeTestCheckin(button)});
