// Session identities stay stable when an opportunity is rescheduled.
function schedule(){return courseSchedules[course()]}
function teamIndex(){return schedule().teams.findIndex(t=>t.includes(student()))}
function teamLabel(i){return schedule().teams[i].join(' · ')}
function sessionKey(i){return `${course()}:workout-${i+1}`}
function sessionStatus(i){return schedule().sessions[i].deferred?'Awaiting alternate opportunity':state.sessions[sessionKey(i)]||'Scheduled'}
function displayWorkoutDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return value;const [y,m,d]=value.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'America/Phoenix'}).format(new Date(Date.UTC(y,m-1,d,12)))}
function displayWorkoutTime(value){return String(value||'').replace(/(\d{1,2}:\d{2})\s*[–-]\s*(\d{1,2}:\d{2})$/, '$1–$2 AM')+' (Arizona time)'}
function sessionLabel(i){const s=schedule().sessions[i];return s.deferred?`Date to be determined (previously ${displayWorkoutDate(s.originalDate)}, ${displayWorkoutTime(s.originalTime)})`:`${displayWorkoutDate(s.date)} · ${displayWorkoutTime(s.time)}`}
function assignment(kind){const field=kind==='shared'||kind==='individual'?'teach':kind===0?'desk':'support';return schedule().sessions.findIndex(s=>s[field]===teamIndex())}
function assignmentLabel(kind){const i=assignment(kind);return i<0?'Awaiting assignment':sessionLabel(i)}
function roleDeferred(i){const n=assignment(i);return n<0||schedule().sessions[n].deferred}
function studentParticipation(){return schedule().sessions.map((s,i)=>({s,i})).filter(({s})=>s.participants.includes(teamIndex()))}
function assessmentKey(kind,i){const session=kind==='role'?assignment(i):kind==='participation'?i:assignment('individual');return `${course()}:${kind==='shared'?'team-'+teamIndex():student()}:workout-${session+1}:${kind}:${i}`}
function syncTeams(){const select=$('#team');if(!select)return;select.innerHTML='<option value="all">All teams</option>'+schedule().teams.map((t,i)=>`<option value="${i}">${esc(t.join(' · '))}</option>`).join('');select.value='all'}
function syncStudents(){const select=$('#student'),filter=$('#team')?.value||'all',names=filter==='all'?schedule().teams.flat():schedule().teams[Number(filter)]||schedule().teams.flat(),previous=select.value;select.innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');select.value=names.includes(previous)?previous:names[0]}
let sessionNotice={};
function setSessionStatus(i,status){if(!schedule().sessions[i]||schedule().sessions[i].deferred)return;const k=sessionKey(i);state.sessions[k]=status;sessionNotice[k]=status==='Completed'?(typeof cloudTestMode!=='undefined'&&!cloudTestMode?'Workout ended. Changes are saving. Refresh participant feedback to check email delivery; eligible invitations are processed within five minutes.':'Workout ended in preview mode. No emails are sent.'):status==='Scheduled'?'Workout restored to Scheduled. Check-in is open again. Invitations already sent remain recorded.':'Workout status changed to '+status+'.';if(status==='Completed'&&(typeof cloudActive==='undefined'||!cloudActive)){for(const c of state.checkins.filter(c=>c.session===k&&c.consent)){if(!state.queue.some(q=>q.checkin===c.id))state.queue.push({id:crypto.randomUUID(),checkin:c.id,session:k,email:c.email,status:'Preview only',created:new Date().toISOString()})}}else if(status!=='Completed')state.queue=state.queue.filter(q=>q.session!==k)}
function addCheckin(i,email,consent,name='Test participant'){name=String(name||'').trim();if(!name||name.length>100)return 'Enter a name of 100 characters or fewer.';email=String(email||'').trim().toLowerCase();if(!Number.isInteger(i)||!schedule().sessions[i])return 'Choose a workout.';if(!/^[a-z0-9._+-]+@example\.com$/.test(email))return 'Use a fictional address ending in @example.com for this test.';const k=sessionKey(i);if(schedule().sessions[i].deferred||['Completed','Canceled'].includes(sessionStatus(i)))return 'Check-in is closed for this workout.';if(state.checkins.some(c=>c.session===k&&c.email===email))return 'This sample address is already checked in for this workout.';state.checkins.push({id:crypto.randomUUID(),session:k,name,email,consent:!!consent,test:true,created:new Date().toISOString()});return ''}
function scheduleView(){return `<h2>Workout schedule · ${esc(course())}</h2><p>Loaded from your schedules. Scores are blank until you enter an assessment. Select a student to retrieve their teaching, roles and participation across dates.</p>${schedule().sessions.map((r,i)=>`<article><h3>${esc(sessionLabel(i))}</h3><p>Teaching: ${esc(teamLabel(r.teach))}<br>Front Desk / On Deck: ${esc(teamLabel(r.desk))}<br>Workout Support: ${esc(teamLabel(r.support))}</p>${r.equipment?`<p>Required equipment: ${esc(r.equipment)}</p>`:''}<p>Participating: ${r.participants.map(t=>esc(teamLabel(t))).join('; ')||'To be assigned when the opportunity is scheduled'}</p>${r.note?`<p class="warning">${esc(r.note)} No zero is assigned for a deferred opportunity.</p>`:''}<p>Status: <strong>${sessionStatus(i)}</strong> · ${typeof cloudTestMode==='undefined'||cloudTestMode?'Test check-ins':'Participant check-ins'}: ${state.checkins.filter(c=>c.session===sessionKey(i)).length}</p>${sessionNotice[sessionKey(i)]?`<p class="panel" role="status">${esc(sessionNotice[sessionKey(i)])}</p>`:''}${checkinRoster(i)}${r.deferred?'':`<div class="scores">${['Scheduled','In progress','Delayed','Completed','Canceled'].map(status=>`<button data-session="${i}" data-session-action="${status}">${status==='Completed'?(typeof cloudTestMode!=='undefined'&&!cloudTestMode?'End workout & queue feedback emails':'End workout / preview invitations'):status==='Scheduled'?'Restore Scheduled':status}</button>`).join('')}</div>`}</article>`).join('')}<h2>Workout evaluation invitations</h2><p>${state.emailStatus?.mode==='live'?'Email delivery is active for eligible consenting participants.':'Preview mode · No emails are sent.'} ${state.emailStatus?.configured?'Email connection settings are present.':'Email connection has not been configured.'}</p><p>End the workout, then refresh participant feedback to see prepared invitations.</p>${state.queue.filter(q=>q.session.startsWith(course()+':')).map(q=>`<article><p>${esc(q.email)} · ${esc(q.session)} · ${esc(q.status)}</p><p><strong>Subject:</strong> ${esc(q.subject||'How was your MCC workout?')}</p>${q.text?`<p class="preserve-lines">${esc(q.text)}</p>`:'<p>Refresh participant feedback to retrieve the invitation preview.</p>'}${/^\/evaluation\.html\?session=EXS(?:215|217)%3Aworkout-\d+&token=[a-f0-9]{48}$/.test(q.evaluationPath||'')?`<p><a href="${esc(q.evaluationPath)}" target="_blank" rel="noopener noreferrer">Open evaluation preview</a></p>`:`<p>Refresh participant feedback to retrieve shared evaluation links.</p>`}</article>`).join('')||'<p>No invitations prepared.</p>'}`}
let checkinSelection={};
function checkinOptions(){return schedule().sessions.map((r,i)=>({r,i})).filter(({r,i})=>!r.deferred&&!['Completed','Canceled'].includes(sessionStatus(i)))}
function checkinView(){const options=checkinOptions();let selected=checkinSelection[course()];if(!options.some(o=>o.i===selected))selected=options[0]?.i;checkinSelection[course()]=selected;const r=schedule().sessions[selected];return `<div class="checkin-card"><p class="eyebrow">MCC · EXERCISE SCIENCE</p><h2>Workout participant check-in</h2><p>Welcome! Everyone attending this workout checks in here.</p><p class="test-notice">Test preview · Use a fictional name and an @example.com email. No emails are sent.</p>${options.length?`<label class="workout-selector" for="checkin-session">Front desk: select the workout team<select id="checkin-session" form="checkin-form" name="session">${options.map(({r,i})=>`<option value="${i}" ${i===selected?'selected':''}>${esc(teamLabel(r.teach))} · ${esc(sessionLabel(i))}</option>`).join('')}</select></label><div class="workout-badge"><strong>${esc(teamLabel(r.teach))}</strong><span>${esc(sessionLabel(selected))}</span></div><form id="checkin-form"><label for="checkin-name">Your name<input id="checkin-name" name="name" autocomplete="off" maxlength="100" required placeholder="Full name"></label><label for="checkin-email">Email address<input id="checkin-email" name="email" type="email" autocomplete="off" spellcheck="false" required placeholder="participant@example.com" aria-describedby="email-use"></label><p id="email-use" class="muted">Your email is used for this workout’s evaluation invitation.</p><label class="checkin-consent"><input name="consent" type="checkbox"> Email me a brief evaluation after this workout.</label><div id="checkin-error" role="alert"></div><button class="checkin-submit" type="submit">Check In</button></form>`:'<p>No workouts are open for check-in. Please ask the front desk for help.</p>'}<p id="checkin-confirmation" role="status" aria-live="polite" tabindex="-1"></p></div>`}


function checkinRoster(i){const rows=[...state.checkins,...(state.excludedCheckins||[])].filter(c=>c.session===sessionKey(i));return rows.length?`<details><summary>View ${rows.length} check-in record${rows.length===1?'':'s'}</summary><div class="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Evaluation invitation</th><th>Test cleanup</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name||'Test participant')}</td><td>${esc(r.email)}</td><td>${r.excluded?'Excluded test entry':r.consent?'Requested':'Not requested'}</td><td>${typeof cloudActive!=='undefined'&&cloudActive&&/^[a-f0-9]{64}$/.test(r.id)?`<button data-exclude-checkin="${esc(r.id)}" data-exclude-session="${esc(r.session)}" data-restore-entry="${r.excluded?'true':'false'}">${r.excluded?'Restore entry':'Exclude test entry'}</button>`:''}</td></tr>`).join('')}</tbody></table></div></details>`:''}
