const {randomUUID}=require('node:crypto');
const SITE='https://exs-workout-feedback.netlify.app';
function invitation(entry,session){const when=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'America/Phoenix'}).format(new Date(session.date+'T12:00:00Z'));const time=String(session.time).replace(/(\d{1,2}:\d{2})\s*[–-]\s*(\d{1,2}:\d{2})$/, '$1–$2 AM')+' (Arizona time)';const link=SITE+'/evaluation.html?session='+encodeURIComponent(entry.session)+'&token='+entry.token;return {to:entry.email,subject:'How was your MCC workout?',text:`Thank you for joining our workout on ${when}, ${time}.\n\nPlease share your experience in three quick questions and one optional comment:\n${link}\n\nYour feedback helps our student teaching team improve. You do not need to identify individual instructors.\n\nYou received this invitation because you requested a workout evaluation at check-in. Completing it is optional.\n\nMesa Community College · Exercise Science`}}
async function replace(store,key,id,update){for(let attempt=0;attempt<5;attempt++){const prior=await store.getWithMetadata(key,{type:'json',consistency:'strong'});if(!prior)return false;const entry=prior.data.find(e=>e.id===id);if(!entry)return false;const changed=update(entry);if(!changed)return false;const result=await store.setJSON(key,prior.data.map(e=>e.id===id?changed:e),{onlyIfMatch:prior.etag});if(result.modified)return true}return false}
async function processInvitations({store,schedules,statuses,live=false,testMode=true,deliver,limit=3,now=()=>new Date().toISOString()}){
 const result={mode:live&&!testMode?'live':'preview',pending:0,sent:0,needsReview:0};
 const sessions=Object.entries(schedules).flatMap(([course,data])=>data.sessions.map((s,i)=>({...s,key:course+':workout-'+(i+1)}))).filter(s=>!s.deferred&&statuses[s.key]==='Completed');
 for(const session of sessions){const prior=await store.getWithMetadata(session.key,{type:'json',consistency:'strong'});for(const entry of prior?.data||[]){if(!entry.consent||entry.evaluation||entry.delivery)continue;result.pending++;if(result.mode!=='live'||result.sent+result.needsReview>=limit)continue;
 // Test-marked records and example addresses are never eligible for live delivery.
 if(entry.test!==false||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(entry.email)||/@example\.(com|org|net)$/i.test(entry.email))continue;
 const claim=randomUUID();const claimed=await replace(store,session.key,entry.id,e=>!e.consent||e.evaluation||e.delivery?null:{...e,delivery:{status:'sending',claim,started:now()}});if(!claimed)continue;
 try{const response=await deliver(invitation(entry,session));const marked=await replace(store,session.key,entry.id,e=>e.delivery?.claim===claim?{...e,delivery:{...e.delivery,status:'sent',sent:now(),messageId:response?.messageId||null}}:null);if(marked)result.sent++;else result.needsReview++}catch{await replace(store,session.key,entry.id,e=>e.delivery?.claim===claim?{...e,delivery:{...e.delivery,status:'needs-review',reviewedAt:now()}}:null);result.needsReview++}
 }}return result;
}
module.exports={invitation,processInvitations};
